// User
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED'
// Repos
export const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST'
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS'
export const FETCH_REPOS_FAILED = 'FETCH_REPOS_FAILED'
